include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - bricks/**/*.dart

linter:
  rules:
    always_specify_types: true
    omit_local_variable_types: false
    public_member_api_docs: false
    prefer_expression_function_bodies: true
    sort_constructors_first: false
