name: flutter_packages_a_z
description: Flutter Packages A-Z.
publish_to: "none"
version: 0.1.0

environment:
  flutter: ">=3.13.0 <4.0.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  beamer: ^1.5.6
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_deck: ^0.5.0
  flutter_hooks: ^0.20.1
  flutter_osm_plugin: ^0.60.5
  flutter_riverpod: ^2.4.3
  flutter_zoom_drawer: ^3.1.1
  fluttertoast: ^8.2.2
  fpdart: ^1.1.0
  get_it: ^7.6.2
  go_router: ^11.1.3
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  just_audio: ^0.9.34
  lottie: ^2.6.0
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  wakelock_plus: ^1.1.1
  xml: ^6.3.0
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/
  uses-material-design: true
