name: flutter_packages_a_z
description: Flutter Packages A-Z.
publish_to: "none"
version: 0.1.0

environment:
  flutter: ">=3.13.0 <4.0.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  beamer: ^1.5.6
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_deck: ^0.3.0
  fpdart: ^1.1.0
  get_it: ^7.6.2
  go_router: ^10.1.2
  just_audio: ^0.9.34
  lottie: ^2.6.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/
  uses-material-design: true
